name: si-actions
run-name: Ciao da ${{ github.actor }} 
on: [push]
jobs:
  si-fa-cose:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Fineeeeeeeeeeeeeeeeeeeeeeeeeeee"

  si:
    runs-on: ubuntu-latest
    steps:
      - run: java -version
  exec:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK for x64
        # https://github.com/actions/setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.2'
          distribution: 'temurin
      - uses: actions/checkout@v4
      - run: |
          cd javademo
          mvn install 
        