name: si-actions
run-name: Ciao da ${{ github.actor }} 
on: 
  push:
  pull_request_target:
  
jobs:
  si-fa-cose:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Fineeeeeeeeeeeeeeeeeeeeeeeeeeee"

  si:
    runs-on: ubuntu-latest
    steps:
      - run: java -version

  exec:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK for x64
        # https://github.com/actions/setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.2'
          distribution: 'temurin'
      - uses: actions/checkout@v4
        with: #non fare al lavoro
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          cd javademo
          mvn clean install -Dmaven.test.skip=true
      - run: |
          cd javademo
          mvn test   

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd javademo
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=immortalis202_onlyvolunteering \
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} \
            -Dsonar.pullrequest.base=main \
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }} \
            -Dmaven.test.skip=true
           
      - run: java -cp target/my-app-1.0-SNAPSHOT.jar com.mycompany.app.App
        working-directory: javademo
      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: my-app-1.0-SNAPSHOT.jar

          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: javademo/target/my-app-1.0-SNAPSHOT.jar
      - uses: actions/upload-artifact@v4
        with: 
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: my-app-1.0-SNAPSHOT-jar-with-dependencies.jar

          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: javademo/target/my-app-1.0-SNAPSHOT-jar-with-dependencies.jar
