name: si-actions
run-name: Ciao da ${{ github.actor }} 
on: [push]
jobs:
  si-fa-cose:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Fineeeeeeeeeeeeeeeeeeeeeeeeeeee"

  si:
    runs-on: ubuntu-latest
    steps:
      - run: java -version
  exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd javademo
          mvn install 
        